name: 'code'

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/code.yaml'
    - 'package.json'
    - 'src/**'
    - 'tests/*'
    - 'tsconfig.json'
    - 'tslint.json'
  pull_request:
    paths:
    - '.github/workflows/code.yaml'
    - 'package.json'
    - 'src/**'
    - 'tests/*'
    - 'tsconfig.json'
    - 'tslint.json'

jobs:
  test:
    name: lint, test and build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v3
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: Lint code
      run: yarn lint
    - name: Test code
      run: yarn test
    - name: Build code
      run: yarn build
    - name: Upload built code
      uses: actions/upload-artifact@master
      with:
        name: build
        path: lib/
  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v3
      with:
        ref: refs/heads/releases/v1
    - name: Download build
      uses: actions/download-artifact@master
      with:
        name: build
        path: lib/
    - name: Install prod yarn dependencies
      run: yarn --prod
    - name: Commit release
      run: |
        rm .gitignore
        git config --local user.email "android18@minddoc.de"
        git config --local user.name "Android 18"
        git config --local github.user "minddocbot"
        git config --local github.email "android18@minddoc.de"
        git add node_modules lib
        git commit -a -m "Release version v1"
    - name: Push release commit
      uses: ad-m/github-push-action@master
      with:
        branch: refs/heads/releases/v1
        github_token: ${{ github.token }}
